### PR TITLE
VMR move constants

### PR DESCRIPTION
**Pull request by meisonlikesicecream**
As requested, moved some VMR constants from top-level files to the parameters files. Also moved some constants to the Constants.h file.

While changing the top-level files, I also cleaned up the generate_VMR* scripts and fixed some bugs.

Added implementation for testing all VMRs when running the tcl scripts. All modules pass CSim using the new testvectors in https://github.com/cms-L1TK/firmware-hls/pull/220 (haven't tried it for the current ones).

### CODE REVIEW

**Comment by meisonlikesicecream** [comment]
@aehart marked this as a draft as I wasn't sure if I should wait until the fw synch has been merged?

**Comment by meisonlikesicecream** [comment]
@carriganm95 would you mind checking that I have moved everything you wanted me to move? Note that I also moved/changed some constants that were in the VMRouterCM.h file: don't know if that will affect the future emulation or not.

**Comment by meisonlikesicecream** [comment]
CI fails because current test vectors sometimes contain 108 processed stubs while the VMRs only can do 107 now. Will be fixed with the fw synch.

**Comment by carriganm95** [comment]
> @carriganm95 would you mind checking that I have moved everything you wanted me to move? Note that I also moved/changed some constants that were in the VMRouterCM.h file: don't know if that will affect the future emulation or not.

This works on the future SW side. thanks

**Review by aehart — APPROVED** [review]
@meisonlikesicecream Thank you for the well-written code. Approved!

**Pull request merged**
