### PR TITLE
Reduced config ir checked

### PR DESCRIPTION
**Pull request by sseifeln**
IR modified to work in both the reduced configuration and the master branch.

### CODE REVIEW

**Comment by tschuh** [comment]
https://github.com/cms-L1TK/firmware-hls/blob/1eafa9b8ba36efbb0abc7cd301b342d1cc806a8c/project/script_IR.tcl#L62
should be

**Comment by tschuh** [comment]
https://github.com/cms-L1TK/firmware-hls/blob/1eafa9b8ba36efbb0abc7cd301b342d1cc806a8c/project/script_IR.tcl#L123
shall be
`# Link 9`
and
https://github.com/cms-L1TK/firmware-hls/blob/1eafa9b8ba36efbb0abc7cd301b342d1cc806a8c/project/script_IR.tcl#L145
shall be
`# Link 11`

**Comment by tschuh** [comment]
Link 16 fails cosim with error:
`ERROR: [COSIM 212-330] Aborting co-simulation: top function 'InputRouterTop_IR_DTC_2S_4_B' is not invoked in the test bench.`
I am using cosim to get the value of `hPhBnWord_V`, could you please give me the hex value of that for this module?

**Comment by tschuh** [comment]
When I run script_IR I am getting the following error
`ERROR: [SYNCHK 200-79] Cannot find the top function 'solution_PS10G_3_A' in the design. Possible causes are: (1) the top function name is misspelled; (2) the top function is nonexistent or declared as static.`
`ERROR: [HLS 200-70] Synthesizability check failed.`

**Comment by tschuh** [comment]
https://github.com/cms-L1TK/firmware-hls/blob/1d8cc463ae76db257cde4f6a3a0875c8f1160c65/project/script_IR.tcl#L62
shall be
`set_top InputRouterTop_IR_DTC_PS10G_3_A`
I guess

**Comment by tschuh** [comment]
I am still getting the cosim error described above, can you please fix that?

**Comment by sseifeln** [comment]
No longer needed - changes pushed directly to reduced_config_pr

**Pull request closed without merging**
