### PR TITLE
Top level generation script for ME

### LINKED ISSUE #177: Scripts to generate top functions
There is currently a Python script that can generate the supported top functions of the TC from the wiring configuration:
https://github.com/cms-L1TK/firmware-hls/blob/master/emData/generate_TC.py
This script also generates all the bit masks and other constants that are unique to each instance of the TC.

All of the modules should have similar scripts written for them that generate top functions from a given wiring configuration, at least for the instances that will appear in the summer chain (L1L2 seeds with matches only in the barrel).

### PR DESCRIPTION
**Pull request by aperloff**
This resolved #177 for the ME and is similar in spirit to #178. It relies upon #183 and will need to be rebased after that is merged. This PR would also benefit from #179, though that is not strictly required.

There is one open question remaining. Right now the script will create a new top level function for each module in the wiring file (i.e. ME_L3PHIC20). However, the ME code doesn't really change based on the phi sector (PHIC20 in this example). It only depends on the layer/disk. The code could be changed to only generate one module per layer/disk, which would save on time when synthesizing all of the modules. However, this change is not strictly necessary.

### CODE REVIEW

**Comment by aperloff** [comment]
@aehart This PR is now ready for review. It has been rebased on top of the master branch. I also implemented a feature in the `generate_ME.py` script to create a single top function for each layer/disk. This is turned on by default in the `download.sh` script.

There are a few features we may want in a future PR:
1. In order for the disk test to be successful #187 will need to be settled.
2. Right now there are specific phi sectors which can be tested due to the hard coding of the test vectors in the test bench. Technically all phi sectors will work, but it's not convenient to test all 288 modules. Implementing #182 might make it easier to allow for the automated testing of more phi sectors.
Neither of these are necessary or should hold up this PR. I just want to put them here for the record.

**Comment by pwittich** [comment]
> @aehart This PR is now ready for review. It has been rebased on top of the master branch. I also implemented a feature in the `generate_ME.py` script to create a single top function for each layer/disk. This is turned on by default in the `download.sh` script.
> 
> There are a few features we may want in a future PR:
> 
> 1. In order for the disk test to be successful [New bit needed in VMStubsMEMemory #187](https://github.com/cms-L1TK/firmware-hls/issues/187) will need to be settled.
> 2. Right now there are specific phi sectors which can be tested due to the hard coding of the test vectors in the test bench. Technically all phi sectors will work, but it's not convenient to test all 288 modules. Implementing [Modify Macros.h to use X-Macros #182](https://github.com/cms-L1TK/firmware-hls/pull/182) might make it easier to allow for the automated testing of more phi sectors.
>    Neither of these are necessary or should hold up this PR. I just want to put them here for the record.

Can you put these comments into new issue(s)? they will disappear when this Pr is closed.

**Comment by aperloff** [comment]
@pwittich I have added a comment to #187 and created issue #197. So these comments will no longer be forgotten.

**Comment by aehart** [comment]
@aperloff This looks very good to me. Can you remove MatchEngineTop.*, since it is now automatically generated?

**Comment by aperloff** [comment]
> @aperloff This looks very good to me. Can you remove MatchEngineTop.*, since it is now automatically generated?

Done, tests running.

**Review by aehart — APPROVED** [review]
Also looks good. Approved!

**Pull request merged**
