### PR TITLE
DR track merger (dummy module) after rebase

### PR DESCRIPTION
**Pull request by kwalkingshaw**
Created a new branch and re-added the Track Merger files inc. test bench, tcl script as the old track_merger branch kept failing the CI after the rebase.

The original PR before this rebase was https://github.com/cms-L1TK/firmware-hls/pull/149 .

### CODE REVIEW

**Comment by tomalin** [comment]
The CI checks are not compiling your code https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/3333068 .  Based on example for TB at L185-189 of https://github.com/cms-L1TK/firmware-hls/blob/track_merger_rebased/.gitlab-ci.yml can you add corresponding code after L189 for DR to do clang code quality checks? And based on TB example at L271-277 that compile TB, can you add corresponding code after L277 to compile DR?

**Comment by tomalin** [comment]
As you can see from the CI check https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/3335832 , this failed the code quality checks.

**Comment by kwalkingshaw** [comment]
The last commit was from me using Sarah's machine as she was helping me debug the CI errors.

**Comment by tomalin** [comment]
The CI code quality check is failing because it can't find TrackMergerTop.cc  and .h . You need to move these from TrackletAlgorithm/ to TopFunctions/

**Comment by kwalkingshaw** [comment]
Okay, have pushed these changes.
________________________________

**Pull request closed without merging**
