### PR TITLE
Match processor2

### PR DESCRIPTION
**Pull request by bryates**

### CODE REVIEW

**Comment by bryates** [comment]
Is the CI broken, or is one of my changes failing? I does not give the normal information I'm used to seeing, where it shows exactly what step failed. All I see is `mirror_trig` failed.

**Comment by bryates** [comment]
I found the complete list [here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/2641968) and it seems to be the VMRCM-quality-check due to the we made in here:
https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/VMStubMEMemoryCM.h#L145

**Comment by meisonlikesicecream** [comment]
> I found the complete list [here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/2641968) and it seems to be the VMRCM-quality-check due to the we made in here:
> https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/VMStubMEMemoryCM.h#L145
> 
> @aryd do you know if these changes are compatible with the other modules?

Nope, a fourth template parameter corresponding to NCOPY needs to be added the ME memories for the VMRCM as well.

**Comment by bryates** [comment]
> > I found the complete list [here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/2641968) and it seems to be the VMRCM-quality-check due to the we made in here:
> > https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/VMStubMEMemoryCM.h#L145
> > 
> > @aryd do you know if these changes are compatible with the other modules?
> 
> Nope, a fourth template parameter corresponding to NCOPY needs to be added the ME memories for the VMRCM as well.

Unfortunately, https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/MemoryTemplateBinnedCM.h#L115 also changed, and I'm not familiar enough with the VMRouterCM to fix the call to the memory slot.

**Comment by aehart** [comment]
@bryates I think the CI tests are failing because you need to rebase to the master branch.

This branch seems to have artifacts from a few botched rebases already. For example, this commit appears to be duplicated 12 times in this branch:
https://github.com/cms-L1TK/firmware-hls/commit/27bbf6b1887a4aae480732692a3f3d47a96097d1
https://github.com/cms-L1TK/firmware-hls/commit/80174f47645b695c83332f6f62b49194304de2ec
https://github.com/cms-L1TK/firmware-hls/commit/19b343c7c12c6f9c994f36dd6f8b881ade530e00
https://github.com/cms-L1TK/firmware-hls/commit/1f500dc737444ebbce532552bf1b03fa9d0b9a1f
https://github.com/cms-L1TK/firmware-hls/commit/d95ea9febfdad3cf66daaec2d4253ca6de02eb4d
https://github.com/cms-L1TK/firmware-hls/commit/a65ba5748ad4129171698eaabdfd2cc3218c8f28
https://github.com/cms-L1TK/firmware-hls/commit/9443435f35e38cf63953b67d59b02a240444c7aa
https://github.com/cms-L1TK/firmware-hls/commit/f7e888821b9b27e908bff83bdf19de004256b937
https://github.com/cms-L1TK/firmware-hls/commit/fd506208937ff6ae57995cd96767158d4bccfe0e
https://github.com/cms-L1TK/firmware-hls/commit/d5c47c4798e08199483674657b971e3b364a892a
https://github.com/cms-L1TK/firmware-hls/commit/4cdec6514b854c34139632166ecd29dce4d89b3c
https://github.com/cms-L1TK/firmware-hls/commit/6209f7d6510a592ac24301a94675e3422ade8067

So when you rebase now, I would recommend using the `--interactive` option:
```bash
$ git fetch origin
$ git rebase --interactive origin/master
```
This will present you with a list of commits that are to be replayed, starting from the HEAD of the master branch. The initial list will be commits that git finds in your development branch but not in the master branch, but you can edit this list before it is applied. You should go through it and remove any duplicate commits or commits that you don't recognize.

**Comment by meisonlikesicecream** [comment]
> > > I found the complete list [here](https://gitlab.cern.ch/cms-l1tk/firmware-hls/-/pipelines/2641968) and it seems to be the VMRCM-quality-check due to the we made in here:
> > > https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/VMStubMEMemoryCM.h#L145
> > > 
> > > @aryd do you know if these changes are compatible with the other modules?
> > 
> > 
> > Nope, a fourth template parameter corresponding to NCOPY needs to be added the ME memories for the VMRCM as well.
> 
> Unfortunately,
> 
> https://github.com/cms-L1TK/firmware-hls/blob/73bc2a63099681af24f010bc2bf148f0d8ce0a9b/TrackletAlgorithm/MemoryTemplateBinnedCM.h#L115
> 
> also changed, and I'm not familiar enough with the VMRouterCM to fix the call to the memory slot.

I could have a look, but I couldn't help but notice that the changes recently made to master (from PR https://github.com/cms-L1TK/firmware-hls/pull/150) are not included here. Could you merge those changes before I can check what to change in the VMRCM?

**Comment by bryates** [comment]
> @bryates I think the CI tests are failing because you need to rebase to the master branch.
> 
> This branch seems to have artifacts from a few botched rebases already. For example, this commit appears to be duplicated 12 times in this branch:
> [27bbf6b](https://github.com/cms-L1TK/firmware-hls/commit/27bbf6b1887a4aae480732692a3f3d47a96097d1)
> [80174f4](https://github.com/cms-L1TK/firmware-hls/commit/80174f47645b695c83332f6f62b49194304de2ec)
> [19b343c](https://github.com/cms-L1TK/firmware-hls/commit/19b343c7c12c6f9c994f36dd6f8b881ade530e00)
> [1f500dc](https://github.com/cms-L1TK/firmware-hls/commit/1f500dc737444ebbce532552bf1b03fa9d0b9a1f)
> [d95ea9f](https://github.com/cms-L1TK/firmware-hls/commit/d95ea9febfdad3cf66daaec2d4253ca6de02eb4d)
> [a65ba57](https://github.com/cms-L1TK/firmware-hls/commit/a65ba5748ad4129171698eaabdfd2cc3218c8f28)
> [9443435](https://github.com/cms-L1TK/firmware-hls/commit/9443435f35e38cf63953b67d59b02a240444c7aa)
> [f7e8888](https://github.com/cms-L1TK/firmware-hls/commit/f7e888821b9b27e908bff83bdf19de004256b937)
> [fd50620](https://github.com/cms-L1TK/firmware-hls/commit/fd506208937ff6ae57995cd96767158d4bccfe0e)
> [d5c47c4](https://github.com/cms-L1TK/firmware-hls/commit/d5c47c4798e08199483674657b971e3b364a892a)
> [4cdec65](https://github.com/cms-L1TK/firmware-hls/commit/4cdec6514b854c34139632166ecd29dce4d89b3c)
> [6209f7d](https://github.com/cms-L1TK/firmware-hls/commit/6209f7d6510a592ac24301a94675e3422ade8067)
> 
> So when you rebase now, I would recommend using the `--interactive` option:
> 
> ```shell
> $ git fetch origin
> $ git rebase --interactive origin/master
> ```
> 
> This will present you with a list of commits that are to be replayed, starting from the HEAD of the master branch. The initial list will be commits that git finds in your development branch but not in the master branch, but you can edit this list before it is applied. You should go through it and remove any duplicate commits or commits that you don't recognize.

Ok, I'll get started on this. There a a LOT of commits, since I didn't do a good job keeping this synced with the master branch. Alternatively, I created the MPtest branch that started with the master, and just copied over the relevant files to make the MP work. We lose the git history with this, but don't we lose it when we rebase anyway?

**Comment by aehart** [comment]
> Ok, I'll get started on this. There a a LOT of commits, since I didn't do a good job keeping this synced with the master branch. Alternatively, I created the MPtest branch that started with the master, and just copied over the relevant files to make the MP work. We lose the git history with this, but don't we lose it when we rebase anyway?

When we rebase, we retain all the original commits. It's just that they are replayed, in order, starting from the HEAD of the master branch.

However, we do usually squash the commits when we merge a PR, and it sounds like you've effectively done that on the MPtest branch. Should we just review that PR instead?

**Comment by bryates** [comment]
> > Ok, I'll get started on this. There a a LOT of commits, since I didn't do a good job keeping this synced with the master branch. Alternatively, I created the MPtest branch that started with the master, and just copied over the relevant files to make the MP work. We lose the git history with this, but don't we lose it when we rebase anyway?
> 
> When we rebase, we retain all the original commits. It's just that they are replayed, in order, starting from the HEAD of the master branch.
> 
> However, we do usually squash the commits when we merge a PR, and it sounds like you've effectively done that on the MPtest branch. Should we just review that PR instead?

Yes, I think that might be the better option. I'll close this one now, and change the other one from a draft to open.

**Pull request closed without merging**
